# Generated by Django 3.2 on 2022-07-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_company_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='USERNAME_FIELD',
        ),
    ]
