# Generated by Django 3.2 on 2022-07-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_company_name_company_username_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='USERNAME_FIELD',
            new_name='company_name',
        ),
    ]
