# Generated by Django 3.2 on 2022-07-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_username_field_company_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='username',
        ),
    ]
